name: .NET

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        working-directory: ./source/validdata.M365.Connectors.OpenApiTools/
        
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: true

    - name: Restore dependencies
      working-directory: ${{env.working-directory}}
      run: dotnet restore

    - name: Build
      working-directory: ${{env.working-directory}}
      run: dotnet build --no-restore

    - name: Test
      working-directory: ${{env.working-directory}}
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
